module ApplicationHelper
	def us_states
		[
			%w[AK Alaska],
			%w[AL Alabama],
			%w[AR Arkansas],
			%w[AS American Samoa],
			%w[AZ Arizona],
			%w[CA California],
			%w[CO Colorado],
			%w[CT Connecticut],
			%w[DC District of Columbia],
			%w[DE Delaware],
			%w[FL Florida],
			%w[GA Georgia],
			%w[GU Guam],
			%w[HI Hawaii],
			%w[IA Iowa],
			%w[ID Idaho],
			%w[IL Illinois],
			%w[IN Indiana],
			%w[KS Kansas],
			%w[KY Kentucky],
			%w[LA Louisiana],
			%w[MA Massachusetts],
			%w[MD Maryland],
			%w[ME Maine],
			%w[MI Michigan],
			%w[MN Minnesota],
			%w[MO Missouri],
			%w[MS Mississippi],
			%w[MT Montana],
			%w[NC North Carolina],
			%w[ND North Dakota],
			%w[NE Nebraska],
			%w[NH New Hampshire],
			%w[NJ New Jersey],
			%w[NM New Mexico],
			%w[NV Nevada],
			%w[NY New York],
			%w[OH Ohio],
			%w[OK Oklahoma],
			%w[OR Oregon],
			%w[PA Pennsylvania],
			%w[PR Puerto Rico],
			%w[RI Rhode Island],
			%w[SC South Carolina],
			%w[SD South Dakota],
			%w[TN Tennessee],
			%w[TX Texas],
			%w[UT Utah],
			%w[VA Virginia],
			%w[VI Virgin Islands],
			%w[VT Vermont],
			%w[WA Washington],
			%w[WI Wisconsin],
			%w[WV West Virginia],
			%w[WY Wyoming],
		]
	end
end
